RateMyOrg/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :orgs do
    resources :comments
    resources :ratings
  end
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RateMyOrg/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RateMyOrg/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :org
end

RateMyOrg/app/models/org.rb
class Org < ApplicationRecord
    has_many :comments, dependent: :destroy
    has_many :ratings
end

RateMyOrg/app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :org
end

RateMyOrg/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

RateMyOrg/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
        
    end
    
    def create
        @org = Org.find(params[:org_id])
        @comment = @org.comments.create(comment_params)
        redirect_to org_path(@org)
    end
    
    def destroy
        @org = Org.find(params[:org_id])
        @comment = @org.comments.find(params[:id])
        @comment.destroy
        redirect_to org_path(@org)
    end
    
    private
        def comment_params
            params.require(:comment).permit(:body)
        end
end

RateMyOrg/app/controllers/orgs_controller.rb
class OrgsController < ApplicationController
    
    def index
        @orgs = Org.all
    end
    
    def show
        @org = Org.find(params[:id])
    end
    
    def new
        
    end
    
    def create
        @org = Org.new(org_params)
        
        @org.save
        redirect_to @org
    end
    
    def destroy
        @org = Org.find(params[:id])
        @org.destroy
        
        redirect_to orgs_path
    end
    
    def edit
        @org = Org.find(params[:id])
    end
    
    def update
        @org = Org.find(params[:id])
        
        if @org.update(org_param)
            redirect_to @org
        else
            render 'edit'
        end
        
    end
end

private
 def org_params
     params.require(:orgs).permit(:name, :description, :contact)
 end
 
 def org_param
     params.require(:org).permit(:name, :description, :contact)
 end

RateMyOrg/app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
    def new
    end
    
    def create
        @org = Org.find(params[:org_id])
        @rating = @org.ratings.create(rating_params)
        redirect_to org_path(@org)
    end
    
    def destroy
        @org = Org.find(params[:org_id])
        @rating = @org.ratings.find(params[:id])
        @rating.destroy
        redirect_to org_path(@org)
    end
    
    private
        def rating_params
            params.require(:rating).permit(:rate)
        end
end

RateMyOrg/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

RateMyOrg/app/helpers/application_helper.rb
module ApplicationHelper
end

RateMyOrg/app/helpers/comments_helper.rb
module CommentsHelper
end

RateMyOrg/app/helpers/orgs_helper.rb
module OrgsHelper
end

RateMyOrg/app/helpers/ratings_helper.rb
module RatingsHelper
end

RateMyOrg/app/helpers/welcome_helper.rb
module WelcomeHelper
end

RateMyOrg/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RateMyOrg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

RateMyOrg/app/views/orgs/edit.html.erb
<link href="https://fonts.googleapis.com/css?family=Open+Sans|PT+Sans+Narrow" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="body-container"> 
  <div class="is-centered title">
    <h1 id="header1">Editing Organization</h1>
  </div>
  <div class="form-container">
    <%= form_for @org do |f| %>
     
      <% if @org.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@org.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @org.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
     
      <p>
        <div class="label-heads">
          <%= f.label :name %><br>
        </div>
        <%= f.text_field :name %>
        
      </p>
     
      <p>
        <div class="label-heads">
          <%= f.label :description %><br>
        </div>
        <%= f.text_field :description %>
      </p>
      
      <p>
        <div class="label-heads">
          <%= f.label :contact %><br>
        </div>
        <%= f.text_field :contact %>
      </p>
     
      <p>
        <%= f.submit 'Update' %>
      </p>
     
    <% end %>
  </div>
  <div class="center-text">
    <%= link_to orgs_path do %>
      <%= image_tag "back.png"  %>
    <% end %>
  </div>
</div>

RateMyOrg/app/views/orgs/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Open+Sans|PT+Sans+Narrow" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="body-container"> 
    <div class="is-centered title">
        <h1 id="header1"><%= link_to 'Organizations', orgs_path, class: "nothing" %></h1>
    </div>

    <div class="is-centered">
        <table>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Contact</th>
                <th>Rating</th>
            </tr>
            <% @orgs.each do |org| %>
                <!-- do the math to find the rating -->
                <% a = 0 %>
                <% if org.ratings.present? %>
                    <% b = 0 %>
                <% else %>
                    <% b = 1 %>
                <% end %>
                <% org.ratings.each do |rate| %>
                    <% a += rate.rate.to_i %>
                    <% b += 1 %>
                <% end %>
                <tr>
                    <td width="30px"><%= org.name %></td>
                    <td width="30px"><%= org.description %></td>
                    <td width="30px"><%= org.contact %></td>
                    <!-- Display the rating -->
                    <td><%= a/b %>
                    <!-- Reset the variables for the next org -->
                        <% a = 0 %>
                        <% b = 1 %></td>
                    
                    <td><%= link_to org_path(org) do %>
                                       <%= image_tag "show.png", height: '30', width: '30'  %>
                                     <% end %></td>
                    <td class="Edit"><%= link_to edit_org_path(org) do %>
                                       <%= image_tag "edit.png" %>
                                     <% end %></td>
                    <td><%= link_to org_path(org), method: :delete, data: {confirm: 'Are you sure you want to delete this organization?'} do %>
                                      <%= image_tag("delete.png") %>
                                    <% end %>
                                    </td>
                </tr>
            <% end %>
        </table>
    </div>
    <br>
    <table>
        <div class="is-centered">
            <%= link_to 'Add Organization', new_org_path %>
        </div>
    </table>
    <div class="center-text drop">
        <%= link_to root_path do %>
           <%= image_tag("back.png", alt: "back")  %>
        <% end %>
    </div>
</div>

RateMyOrg/app/views/orgs/new.html.erb
<link href="https://fonts.googleapis.com/css?family=Open+Sans|PT+Sans+Narrow" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="body-container"> 
    <div class="is-centered title">
        <h1 id="header1">Adding Organization</h1>
    </div>
    <div class="form-container">
        <%= form_for :orgs, url: orgs_path do |f| %>
            <p>
                <div class="label-heads">
                    <%= f.label :name %><br>
                </div>
                <%= f.text_field :name %>
            </p>
            
            <p>
                <div class="label-heads">
                    <%= f.label :description %><br>
                </div>
                <%= f.text_field :description %>
            </p>
            
            <p>
                <div class="label-heads">
                    <%= f.label :contact %><br>
                </div>
                <%= f.text_field :contact %>
            </p>
            
            <p>
                <%= f.submit 'Submit' %>
            </p>
        <% end %>
    </div>
    
    <div class="center-text">
        <%= link_to orgs_path do %>
           <%= image_tag("back.png", alt: "back")  %>
        <% end %>
    </div>
</div>

RateMyOrg/app/views/orgs/show.html.erb
<link href="https://fonts.googleapis.com/css?family=Open+Sans|PT+Sans+Narrow" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="body-container"> 
    <div class="is-centered title">
        <h1 id="header1">Organization Details</h1>
    </div>
    <div class="des-container">
        <p>
            <div class="more-heads squeeze">
                <strong>Name:</strong> <%= @org.name %>
            </div>
        </p>
        
        <p>
            <div class="more-heads squeeze">
                <strong>Description:</strong> <%= @org.description %>
            </div>
        </p>
        
        <p>
            <div class="more-heads squeeze">
                <strong>Contact:</strong> <%= @org.contact %>
            </div>
        </p>
        
        <!-- Ask user to leave a rating -->
        <p>
            <% a = 0 %>
            <% if @org.ratings.present? %>
                <% b = 0 %>
            <% else %>
                <% b = 1 %>
            <% end %>
            <% @org.ratings.each do |rate| %>
                <% a += rate.rate.to_i %>
                <% b += 1 %>
            <% end %>
            <div class="more-heads">
                <strong>Rating:</strong> <%= a/b %>
            </div>
        </p>
        
        <!-- form to submit the rating -->
        <%= form_for([@org, @org.ratings.build]) do |f| %>
          <p>
              <div class="additional-head" id="rate-space">
                  <%= f.label :rate, 'Leave a Rating' %>
              </div>
              <%= f.number_field(:rate, in: 0..5) %>
          </p>
          
          <!-- submit button for rating -->
          <div class="move-this-too">
              <p>
                  <%= f.submit 'Rate' %>
              </p>
          </div>
          
        <% end %>
        
        <!-- List all comments -->
        <h2>Comments:</h2>
        <% @org.comments.each do |comment| %>
          <p class="squeeze">
          <strong>Anonymous:</strong>
            <%= comment.body %>
            <%= link_to [comment.org, comment], method: :delete, data: { confirm: 'Are you sure you want delete this comment?' } do %>
                <%= image_tag("delete.png") %>
            <% end %>
          </p>
         <% end %>
        </div>
        <div class="form-container">
            <%= form_for([@org, @org.comments.build]) do |f| %>
              <p>
                  <div class="label-heads">
                      <%= f.label 'Leave a Comment' %>
                  </div>
                  <%= f.text_field :body %>
              </p>
              <p class="move-center">
                  <%= f.submit 'Comment' %>
              </p>
        <% end %>
        </div>
        <div class="center-text drop">
            <%= link_to orgs_path do %>
               <%= image_tag "back.png"  %>
            <% end %>
        </div>
    </div>
</div>

RateMyOrg/app/views/welcome/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Open+Sans|PT+Sans+Narrow" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="body-container down"> 
    <!--Logo-->
    <div class="resize is-centered">
        <img id="logo" src="https://advancement.uncc.edu/sites/advancement.uncc.edu/files/media/unc-charlotte-logo.gif" alt="uncc logo" />
    </div>
    
    <!--Header-->
    <div class="is-centered title"> 
        <h1>Rate My Niner Org</h1>
    </div>
    
    <!--Search bar-->
    <form class="example">
        <input type="text" placeholder="Search.." name="search">
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
    
    <!--List of orgs-->
    <div class="is-centered full-list"> 
        <%= link_to 'List of Orgs', controller: 'orgs' %>
    </div>
    
    <footer class="down">
        <div class="foot-container">
            <p>RUBY WARRIORS Copyright © 2018. UNC CHARLOTTE</p>
        </div>
    </footer>
</div>